### ISSUE TITLE
Update pygit2 & libgit2 and upload a new release to pypi

### ISSUE THREAD

**Issue by dbaxa** [uniphil/venvgit2#13]
It would be great if you could update pygit2, libgit2 and upload a new release of venvgit2 to pypi :-)

**Comment by uniphil** [comment]
For sure! @dbaxa any chance you could make a PR with the submodules updated to the latest versions? I'll get to it eventually (or maybe @Graham42 will), but a PR the fastest way if you need it soon, since I don't think either of us are actively using this at the moment.

**Comment by dbaxa** [comment]
@uniphil sure thing :-)

**Comment by dbaxa** [comment]
It looks like @Graham42 has already updated the sub-modules.

**Comment by dbaxa** [comment]
cc @uniphil @Graham42

**Comment by dbaxa** [comment]
cc @Graham42

**Comment by dbaxa** [comment]
Bump.

**Comment by uniphil** [comment]
aak! Sorry @dbaxa !!

**Comment by uniphil** [comment]
@dbaxa I just added you as a collaborator on this repo, so that this doesn't get jammed up by @Graham42 and I forgetting for months on end :disappointed:

Do you also have a pypi account? I can add you to that as well. Until #14 is done (if ever...), at least you'll be able to get the version you need published!

Thanks for the bump, and really sorry for being asleep at the wheel here!

**Comment by dbaxa** [comment]
@uniphil thank you. My pypi username is "dblack".

**Comment by uniphil** [comment]
great, you should have full access on pypi now :smile:

**Comment by dbaxa** [comment]
Thank you!
